version: '3.8'
services:
  noc-app:
    build: .
    container_name: noc-servicenow
    ports:
      - "8080:8080"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./client.html:/usr/share/nginx/html/client.html
      - ./tech.html:/usr/share/nginx/html/tech.html
      - ./incident-detail.html:/usr/share/nginx/html/incident-detail.html
      - ./change-detail.html:/usr/share/nginx/html/change-detail.html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./app.js:/usr/share/nginx/html/app.js